title: "План питания и тренировок"
description: "Ежедневный рацион и утренние тренировки"
baseurl: ""
url: "https://hemypo.github.io"

# подключаем удалённую тему Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes@4.27.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# навигация
nav:
  - title: Рацион сегодня
    url: /today/
  - title: Тренировки
    url: /workouts/
  - title: Список покупок
    url: /shopping/
  - title: Полное меню
    url: /menu/
  - title: Рецепты
    url: /recipes/

# коллекции для рецептов
collections:
  recipes:
    output: true
