title: "План питания и тренировок"
description: "Ежедневный рацион и утренние тренировки"
baseurl: ""
url: "https://hemypo.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-include-cache

nav:
  # ...
collections:
  recipes:
    output: true
