name: Build and Deploy Jekyll site with Minimal Mistakes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Разрешаем выдачу OIDC-токена для deploy-pages
permissions:
  contents: read          # нужно, чтобы Actions мог читать репозиторий
  pages: write            # нужно, чтобы Actions мог пушить в Pages
  id-token: write         # обязательно для получения ACTIONS_ID_TOKEN_REQUEST_URL

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
